/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.designpatterngui.gui;

/**
 *
 * @author Escritorio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dpWorkingArea = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnMultiplayerAccess = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnArchivo = new javax.swing.JMenuItem();
        mnConsola = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpWorkingAreaLayout = new javax.swing.GroupLayout(dpWorkingArea);
        dpWorkingArea.setLayout(dpWorkingAreaLayout);
        dpWorkingAreaLayout.setHorizontalGroup(
            dpWorkingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        dpWorkingAreaLayout.setVerticalGroup(
            dpWorkingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(dpWorkingArea);

        jMenu1.setText("File");

        mnMultiplayerAccess.setLabel("Multiplayer");
        mnMultiplayerAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMultiplayerAccessActionPerformed(evt);
            }
        });
        jMenu1.add(mnMultiplayerAccess);
        mnMultiplayerAccess.getAccessibleContext().setAccessibleName("mnMultiplayerAccess");

        jMenuBar1.add(jMenu1);

        jMenu2.setActionCommand("Exportar");
        jMenu2.setLabel("Exportar");

        mnArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mnArchivo.setIconTextGap(1);
        mnArchivo.setLabel("Archivo");
        mnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArchivoActionPerformed(evt);
            }
        });
        jMenu2.add(mnArchivo);

        mnConsola.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnConsola.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mnConsola.setIconTextGap(1);
        mnConsola.setLabel("Consola");
        mnConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsolaActionPerformed(evt);
            }
        });
        jMenu2.add(mnConsola);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnMultiplayerAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMultiplayerAccessActionPerformed
        MyMultiPlayer player = new MyMultiPlayer();
        this.dpWorkingArea.add(player);
        player.setVisible(true);
    }//GEN-LAST:event_mnMultiplayerAccessActionPerformed

    private void mnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnArchivoActionPerformed

    private void mnConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnConsolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpWorkingArea;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnArchivo;
    private javax.swing.JMenuItem mnConsola;
    private javax.swing.JMenuItem mnMultiplayerAccess;
    // End of variables declaration//GEN-END:variables
}
