/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.designpatterngui.gui;

import com.mycompany.designpatterngui.gui.pane.PnImage;
import com.mycompany.designpatterngui.gui.pane.PnWav;
import com.mycompany.designpatterngui.log.Log;
import com.mycompany.designpatterngui.log.LoggerInterface;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.File;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Escritorio
 */
public class MyMultiPlayer extends javax.swing.JInternalFrame {

    LoggerInterface log = new Log();
    
    /**
     * Creates new form MyMultiplePlayer
     */
    public MyMultiPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnRender = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnOpen.setText("Open File");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        pnRender.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout pnRenderLayout = new javax.swing.GroupLayout(pnRender);
        pnRender.setLayout(pnRenderLayout);
        pnRenderLayout.setHorizontalGroup(
            pnRenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        pnRenderLayout.setVerticalGroup(
            pnRenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnRender);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnOpen))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            try {
                File file = fileChooser.getSelectedFile();
                log.log( file.getName());
                BorderLayout layout = new BorderLayout();
                if (file.getName().indexOf(".jpg") != -1){
                    //RenderImage
                    
                    //deberia ser otro panel
                    //y que el factory cree el panel basado en el file
                    PnImage pn = new PnImage(file);                    
                    pn.setVisible(true);
                    pn.setPreferredSize(new Dimension(400,400));
                    this.pnRender.setLayout(layout);
                    this.pnRender.add(pn);
                    this.pnRender.validate();
                    this.pnRender.repaint();
                    log.log("Renderizado");
                }
                
                if (file.getName().indexOf(".wav") != -1){
                    //Play Wav                    
                    /*AudioInputStream stream = AudioSystem.getAudioInputStream(file);
                    AudioFormat format = stream.getFormat();
                    DataLine.Info info = new DataLine.Info(Clip.class, format);
                    Clip clip = (Clip) AudioSystem.getLine(info);
                    clip.open(stream);
                    clip.start();*/
                    PnWav pn = new PnWav(file);                    
                    pn.setVisible(true);
                    pn.setPreferredSize(new Dimension(400,400));
                    this.pnRender.setLayout(layout);
                    this.pnRender.add(pn);
                    this.pnRender.validate();
                    this.pnRender.repaint();
                    log.log("Renderizado");
                    //this.validate();
                    //this.repaint();
                    
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
           log.log("Open command canceled");
        }
    }//GEN-LAST:event_btnOpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnRender;
    // End of variables declaration//GEN-END:variables
}
